(()=>{"use strict";
const els={form:document.getElementById("jobSearchForm"),q:document.getElementById("jobQuery"),country:document.getElementById("jobCountry"),discipline:document.getElementById("jobDiscipline"),match:document.getElementById("jobMatch"),availability:document.getElementById("jobAvailability"),sort:document.getElementById("jobSort"),grid:document.getElementById("job-results"),count:document.getElementById("resultCount"),summary:document.getElementById("filterSummary"),total:document.getElementById("totalJobs"),breakdown:document.getElementById("listingBreakdown"),more:document.getElementById("loadMore"),empty:document.getElementById("jobsEmpty"),emptyReset:document.getElementById("emptyReset"),menu:document.getElementById("menu"),nav:document.getElementById("navlinks")};
let jobs=[],limit=24;
const escapeHtml=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const safeUrl=value=>{try{const url=new URL(value);return /^https?:$/.test(url.protocol)?url.href:"#"}catch{return"#"}};
const initials=name=>name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join("").toUpperCase();
const optionize=(select,values)=>{values.filter(Boolean).sort((a,b)=>a.localeCompare(b)).forEach(value=>{const option=document.createElement("option");option.value=value;option.textContent=value;select.append(option)})};
const matchRank=value=>({"Excellent":3,"Strong":2,"Good":1}[value]||0);
function visibleJobs(){const q=els.q.value.trim().toLowerCase(),country=els.country.value,discipline=els.discipline.value,match=els.match.value,availability=els.availability.value;const filtered=jobs.filter(job=>(!q||[job.title,job.company,job.location,job.country,job.discipline].some(v=>String(v).toLowerCase().includes(q)))&&(!country||job.country===country)&&(!discipline||job.discipline===discipline)&&(!match||job.match===match)&&(!availability||job.availability===availability));return filtered.sort((a,b)=>els.sort.value==="company"?a.company.localeCompare(b.company):els.sort.value==="match"?matchRank(b.match)-matchRank(a.match)||(b.dateFound||"").localeCompare(a.dateFound||""):(b.dateFound||"").localeCompare(a.dateFound||""))}
function card(job){const matchClass=job.match==="Excellent"?"match-excellent":job.match==="Strong"?"match-strong":"";const deadline=job.deadline||job.urgency||"Not published";return `<article class="job-card"><div class="job-card-top"><div class="job-company"><span class="company-mark" aria-hidden="true">${escapeHtml(initials(job.company))}</span><div><strong title="${escapeHtml(job.company)}">${escapeHtml(job.company)}</strong><small>${escapeHtml(job.country)}</small></div></div><span class="listing-state ${job.availability==="Archived"?"archived":""}">${escapeHtml(job.availability)}</span></div><h2>${escapeHtml(job.title)}</h2><div class="job-tags"><span class="${matchClass}">${escapeHtml(job.match||"Curated")}</span><span>${escapeHtml(job.discipline)}</span></div><div class="job-meta"><span>Location <b>${escapeHtml(job.location||job.country)}</b></span><span>Date found <b>${escapeHtml(job.dateFound||"Not recorded")}</b></span><span>Deadline <b>${escapeHtml(deadline)}</b></span></div><a class="btn btn-primary job-apply" href="${safeUrl(job.url)}" target="_blank" rel="noopener noreferrer nofollow" aria-label="View ${escapeHtml(job.title)} at ${escapeHtml(job.company)}">View original listing →</a></article>`}
function render(){const filtered=visibleJobs(),shown=filtered.slice(0,limit);els.grid.innerHTML=shown.map(card).join("");els.grid.setAttribute("aria-busy","false");els.count.textContent=`${filtered.length.toLocaleString()} ${filtered.length===1?"job":"jobs"} found`;const active=[els.country.value,els.discipline.value,els.match.value,els.availability.value].filter(Boolean);els.summary.textContent=active.length?active.join(" • "):"All tracker listings";els.more.classList.toggle("hidden",shown.length>=filtered.length);els.empty.classList.toggle("hidden",filtered.length!==0)}
function reset(){els.form.reset();els.availability.value="Current";limit=24;render()}
els.grid.innerHTML='<div class="skeleton"></div><div class="skeleton"></div><div class="skeleton"></div>';
fetch("jobs-data.json",{cache:"no-store"}).then(r=>{if(!r.ok)throw new Error("Unable to load jobs");return r.json()}).then(data=>{jobs=Array.isArray(data.jobs)?data.jobs:[];const current=jobs.filter(job=>job.availability==="Current").length,archived=jobs.filter(job=>job.availability==="Archived").length;els.total.textContent=jobs.length.toLocaleString();els.breakdown.textContent=`${current.toLocaleString()} current • ${archived.toLocaleString()} archived`;optionize(els.country,[...new Set(jobs.map(x=>x.country))]);optionize(els.discipline,[...new Set(jobs.map(x=>x.discipline))]);optionize(els.match,[...new Set(jobs.map(x=>x.match))]);render()}).catch(()=>{els.grid.innerHTML="";els.grid.setAttribute("aria-busy","false");els.count.textContent="Job listings are temporarily unavailable";els.summary.textContent="Please try again later";els.breakdown.textContent="Listing counts unavailable";els.empty.classList.remove("hidden")});
els.form.addEventListener("input",()=>{limit=24;render()});els.form.addEventListener("reset",e=>{e.preventDefault();reset()});els.more.addEventListener("click",()=>{limit+=24;render()});els.emptyReset.addEventListener("click",reset);els.menu.addEventListener("click",()=>{const open=els.nav.classList.toggle("open");els.menu.setAttribute("aria-expanded",String(open))});document.querySelectorAll("[data-year]").forEach(x=>x.textContent=new Date().getFullYear());
})();
